data:
  feature: EMG
  root: ../data/fatigue
  subject_list: [1, 2, 3, 4, 5, 6, 7, 8]
  activities: {0: 'Stroop', 1: 'VR', 2: 'Hand grip', 3: 'Biking'}
  encode_list: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  
model:
  name: vae
  num_modes: 236
  layers: [256, 128, 32]

train:
  lr: 0.0001
  batch_size: 64
  epochs: 61
  save_freq: 5
  log_freq: 200
  weight_decay: 0.0
  kl_weight: 0.01

log:
  project: fatigue
  entity: hzzheng
  group: EMG-vae-236
  tag: vae