data:
  feature: EMG
  root: ../data/fatigue
  subject_list: [1, 2, 3, 4, 5, 6, 7, 8]
  activities: {0: 'Stroop', 1: 'VR', 2: 'Hand grip', 3: 'Biking'}
  encode_list: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  
model:
  num_modes: 192
  layers: [256, 128, 16]

train:
  lr: 0.0002
  batch_size: 64
  epochs: 60
  save_freq: 5000
  log_freq: 200
  weight_decay: 0.00001

log:
  project: fatigue
  entity: hzzheng
  group: EMG-encoder