data:
  feature: Pulse
  root: ../data/emg-pulse
  extra_dir: ../data/extra/pulse
  subject_list: [1, 2, 3, 4, 5, 6, 7, 8]
  activities: {0: 'Stroop', 1: 'VR', 2: 'Hand grip', 3: 'Biking'}
  encode_list: [1, 2, 3, 4, 5, 6, 7, 8, 9]

model:
  name: vae
  num_modes: 32
  layers: [32, 32, 16]

train:
  lr: 0.0005
  lr_min: 0.000001
  batch_size: 256
  epochs: 60
  save_freq: 5
  log_freq: 200
  weight_decay: 0.0
  kl_weight: 0.1

log:
  project: fatigue
  entity: hzzheng
  group: Pulse-encoder-vae-extra
  tag: extra-data