data:
  feature: Pulse
  root: ../fft-data/vae-test
  extra_dir: ../fft-data/extra
  subject_list: [1, 2, 3, 4, 6, 7, 8]
  activities: {0: 'biking', 1: 'sleep', 2: 'walking', 3: 'running', 4: 'meditation', 5: 'music', 6: 'gaming', 7: 'weightlift'}
  encode_list: [10]

model:
  name: vae
  num_modes: 32
  layers: [32, 32, 16]

train:
  lr: 0.0005
  lr_min: 0.00001
  batch_size: 256
  epochs: 101
  save_freq: 10
  log_freq: 200
  weight_decay: 0.0
  kl_weight: 0.1
  freq_weight: 0.01

log:
  project: fatigue
  entity: hzzheng
  group: Pulse-vae32-16-extra-v7
  tag: fft-XL-v7