data:
  type: encoded  # clean, raw, encoded
  root_path: ../data/fatigue
  train_subjects: [1, 2, 3, 4, 5, 6, 7, 8]
  test_subjects: [9]
  test_acts: [Stroop, VR, Hand grip, Biking]
  scale: True
  embedding: None

model: 
  name: Transformer
  task_name: forecast
  seq_len: 64
  pred_len: 64
  label_len: 4
  embed_type: 0
  top_k: 5
  enc_in: 37
  dec_in: 1
  c_out: 1
  d_model: 512
  n_heads: 8      # number of heads
  e_layers: 2     # encoder layers
  d_layers: 1     # decoder layers
  d_ff: 2048      # dimension of fcn
  factor: 1       # attention factor
  embed: timeF    # timeF, fixed or learned
  dropout: 0.02
  activation: gelu
  output_attention: False
  freq: s

train:
  epochs: 10
  batch_size: 32
  patience: 10
  lr: 0.001
  lradj: type1
  weight_decay: 0.0001
  log_every: 100

log:
  project: fatigue
  group: imputation
  tag: train8test1-scaled

