data:
  type: encoded  # clean, raw, encoded
  encode_dir: ../fft-data/vae-v7
  root_path: ../data
  train_subjects: [6, 7, 8, 1, 2, 3, 4]
  train_acts: ['Biking', 'VR', 'Hand grip', 'Stroop']
  test_subjects: [5, 9]
  scale: False
  embedding: None
  cols: ['Current (uAmps)', 'Temperature (°C)']
  subset: 1.0

model: 
  name: LSTM
  task_name: classification
  num_classes: 4
  in_dim: 82
  hidden_dim: 512
  num_layers: 4
  seq_len: 1
  pred_len: 0
  label_len: 0
  embed: timeF 
  freq: s

train:
  epochs: 30
  batch_size: 4096
  patience: 10
  lr: 0.01
  lradj: type1
  weight_decay: 0.0
  log_every: 100
  mixup: 0.4
  bandwidth: 0.0

log:
  project: fatigue
  group: classfication-ablation
  tag: ablation-v7-time-lstm

