data:
  type: encoded  # clean, raw, encoded
  encode_dir: ../fft-data/vae-extra-v3
  root_path: ../data/fatigue
  train_subjects: [6, 7, 8, 1, 2, 3, 4]
  test_subjects: [5, 9]
  scale: False
  embedding: None
  cols: ['Current (uAmps)', 'Temperature (°C)']

model: 
  name: MLP
  task_name: classification
  num_classes: 4
  layers: [9840, 4096, 2048, 1024, 4]
  seq_len: 120
  pred_len: 0
  label_len: 0
  d_model: 1024
  embed: timeF 
  freq: s

train:
  epochs: 30
  batch_size: 32
  patience: 10
  lr: 0.0001
  lradj: type1
  weight_decay: 0.0001
  log_every: 100

log:
  project: fatigue
  group: classfication-ablation
  tag: train7test59-ablation-v3-mlp

