data:
  type: encoded  # clean, raw, encoded
  encode_dir: ../fft-data/vae-v7
  root_path: ../data
  train_subjects: [6, 7, 8, 1, 2, 3, 4]
  test_subjects: [5, 9]
  scale: False
  embedding: None
  cols: ['Current (uAmps)', 'Temperature (°C)']
  subset: 0.4

model: 
  name: Transformer
  task_name: classification
  num_classes: 4
  seq_len: 120
  pred_len: 0
  label_len: 0
  embed_type: 0
  top_k: 5
  enc_in: 82  # 64 + 16 + 5 = 85
  dec_in: 1
  c_out: 1
  d_model: 512
  n_heads: 8      # number of heads
  e_layers: 4     # encoder layers
  d_layers: 1     # decoder layers
  d_ff: 2048      # dimension of fcn
  factor: 1       # attention factor
  embed: timeF    # timeF, fixed or learned
  dropout: 0.1
  activation: gelu
  output_attention: False
  freq: s

train:
  epochs: 30
  batch_size: 32
  patience: 15
  lr: 0.0001
  lradj: type1
  weight_decay: 0.0
  log_every: 100
  mixup: 0.4

log:
  project: fatigue
  group: classfication-learned
  tag: train1test59-vae-v7
